# Generated by Django 5.2.1 on 2025-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_brand_description_alter_country_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomposition',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
