# Generated by Django 5.2.1 on 2025-05-18 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_productcomposition_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomposition',
            name='nutrient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nutrient'),
        ),
    ]
