# Generated by Django 5.2.1 on 2025-05-18 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_productcomposition_nutrient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.product'),
        ),
    ]
