# Generated by Django 5.0.6 on 2025-05-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_reviewlog_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='photo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
